name: a
on: workflow_dispatch
jobs:
  version:
    name: Get version
    uses: ./.github/workflows/bump-version.yaml
    with:
      version: minor
  version2:
    name: Get version
    uses: ./.github/workflows/bump-version.yaml
    with:
      message: "test"
      version: minor
