name: Build 8Vim
on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: true
    outputs:
      version_code:
        value: ${{jobs.bump_version.outputs.version_code}}
      version_name:
        value: ${{jobs.bump_version.outputs.version_name}}
jobs:
  build:
    if: ${{inputs.is_release}}
    name: Build app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: v${{inputs.version_name}}
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: temurin
          cache: gradle
      - name: Setup env
        run: |
          echo "${{ secrets.SIGNING_KEYSTORE_BASE64 }}" > keystore-b64.txt
          base64 -d keystore-b64.txt > 8vim/8vim.jks
      - name: Build APK
        env:
          VIM8_BUILD_KEYSTORE_FILE: ./8vim.jks
          VIM8_BUILD_KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          VIM8_BUILD_KEY_ALIAS: ${{ secrets.ALIAS }}
          VIM8_BUILD_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew bundleRelease assembleRelease
      - name: Upload artifact aab
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: |
            8vim/build/outputs/*/release/8vim-release.*
            8vim/build/outputs/mapping/release/mapping.txt
