name: build_release
on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      cmd:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: temurin
          cache: gradle
      - name: Setup env
        run: |
          echo "${{ secrets.SIGNING_KEYSTORE_BASE64 }}" > keystore-b64.txt
          base64 -d keystore-b64.txt > 8vim/8vim.jks
      - name: Build APK
        env:
          VIM8_BUILD_KEYSTORE_FILE: ./8vim.jks
          VIM8_BUILD_KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          VIM8_BUILD_KEY_ALIAS: ${{ secrets.ALIAS }}
          VIM8_BUILD_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew ${{inputs.cmd}}
      - name: Upload artifact aab
        uses: actions/upload-artifact@v3
        with:
          name: aab
          path: |
            8vim/build/outputs/bundle/${{inputs.target}}Release/8vim-${{inputs.target}}-release.aab
            8vim/build/outputs/apk/${{inputs.target}}/release/8vim-${{inputs.target}}-release.apk
