name: bump version
on: workflow_dispatch
jobs:
  release:
    permissions:
      actions: read
      issues: read
      pull-requests: read
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: bump version
        id: vars
        run: |
          set +a
          . ./version.properties
          set -a
          VERSION_CODE=$((VERSION_CODE+1))
          VERSION_NAME=$(echo iteration-$((${VERSION_NAME/iteration-/}+1)))
          echo "VERSION_CODE=$VERSION_CODE" > version.properties
          echo "VERSION_NAME=$VERSION_NAME" >> version.properties
          echo "version_code=$VERSION_CODE" >> $GITHUB_OUTPUT
          echo "version_name=$VERSION_NAME" >> $GITHUB_OUTPUT
      - name: Create Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: changelog-configuration.json
          toTag: ${{github.sha}}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
      - run: |
          result=$(echo "$CHANGELOG" | sed "s/${{github.sha}}/v${{steps.vars.outputs.version_name}}/g")
          echo "$result" > ${{steps.vars.outputs.version_code}}.txt
        env:
          CHANGELOG: ${{steps.github_release.outputs.changelog}}
      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add ${{steps.vars.outputs.version_code}}.txt
          git commit -a -m "chore(bump): release v${{steps.vars.outputs.version_name}}"
          git tag ${{steps.vars.outputs.version_name}}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          tags: true
