name: Bump version
on:
  workflow_call:
    inputs:
      message:
        type: string
      version:
        required: true
        type: string
jobs:
  version:
    name: Get version
    uses: ./.github/workflows/extract-version.yaml
  bump_version:
    needs: version
    runs-on: ubuntu-latest
    outputs:
      version_code: ${{steps.vars.outputs.version_code}}
      version_name: ${{steps.vars.outputs.version_name}}
    steps:
      - name: bump version
        id: vars
        env:
          MAJOR: ${{needs.version.outputs.major}}
          MINOR: ${{needs.version.outputs.minor}}
          PATCH: ${{needs.version.outputs.patch}}
          RC: ${{needs.version.outputs.RC}}
          VERSION: ${{ github.event.inputs.version }}
        run: |
          if [ $VERSION = "rc" ]
          then
            RC=$(($RC+1))
          else
            RC=0
            if [ $VERSION = "patch" ]
            then
              PATCH=$(($PATCH+1))
            else
              PATCH=0
              if [ $VERSION = "minor" ]
              then
                MINOR=$(($MINOR+1))
              else
                MINOR=0
                MAJOR=$(($MAJOR+1))
              fi
            fi
          fi

          echo "MAJOR=$MAJOR" > 8vim/version.properties
          echo "MINOR=$MINOR" >> 8vim/version.properties
          echo "PATCH=$PATCH" >> 8vim/version.properties
          echo "RC=$RC" >> 8vim/version.properties

          echo "version_code=$(( 1000000 * $MAJOR + 10000 * $MINOR + 100 * $PATCH - $RC))" >> $GITHUB_OUTPUT
          if [ $VERSION = "rc" ]
          then
            echo "version_name=$MAJOR.$MINOR.$PATCH-rc.$RC" >> $GITHUB_OUTPUT
          else
            echo "version_name=$MAJOR.$MINOR.$PATCH" >> $GITHUB_OUTPUT
          fi
      - run: echo "${{ inputs.message }}"
