name: echo
on:
  workflow_dispatch:
    inputs:
      whatsnew:
        required: true
        description: Store release message
      version:
        description: |
          Release version.
          If not specifid it will bump the previous version_name
jobs:
  echo:
    permissions:
      actions: read
      issues: read
      pull-requests: read
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
