name: Extract version
on:
  workflow_call:
    outputs:
      major:
        value: ${{jobs.version.outputs.major}}
      minor:
        value: ${{jobs.version.outputs.minor}}
      patch:
        value: ${{jobs.version.outputs.patch}}
      rc:
        value: ${{jobs.version.outputs.rc}}
jobs:
  version:
    name: Get app version
    runs-on: ubuntu-latest
    outputs:
      major: ${{steps.vars.outputs.major}}
      minor: ${{steps.vars.outputs.minor}}
      patch: ${{steps.vars.outputs.patch}}
      rc: ${{steps.vars.outputs.rc}}
    steps:
      - uses: actions/checkout@v3
      - name: Get version
        id: vars
        run: |
          set +a
          . ./8vim/version.properties
          set -a
          echo "major=$MAJOR" >> $GITHUB_OUTPUT
          echo "minor=$MINOR" >> $GITHUB_OUTPUT
          echo "patch=$PATCH" >> $GITHUB_OUTPUT
          echo "rc=$RC" >> $GITHUB_OUTPUT
