name: Extract version
on:
  workflow_call:
    outputs:
      version_code:
        value: ${{jobs.version.outputs.version_code}}
      version_name:
        value: ${{jobs.version.outputs.version_name}}

jobs:
  version:
    name: Get app version
    runs-on: ubuntu-latest
    outputs:
      version_code: ${{steps.vars.outputs.version_code}}
      version_name: ${{steps.vars.outputs.version_name}}
    steps:
      - uses: actions/checkout@v3
      - name: Get version
        id: vars
        run: |
          set +a
          . ./8vim/version.properties
          set -a
          echo "version_code=$VERSION_CODE" >> $GITHUB_OUTPUT
          echo "version_name=$VERSION_NAME" >> $GITHUB_OUTPUT
