name: Merge test

on:
  pull_request_target:
    branches: [main]
    types: [closed]
    paths:
      - "**.gradle"
      - "app/**"
      - "!app/src/main/**.yaml"
jobs:
  build:
    name: Build nightly version
    permissions:
      actions: read
      issues: read
      pull-requests: read
      contents: write
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: temurin
          cache: gradle
      - name: Setup env
        run: |
          echo "date=$(date +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
          echo "ts=$(date +%s)" >> $GITHUB_ENV
          echo "${{ secrets.SIGNING_KEYSTORE_BASE64 }}" > keystore-b64.txt
          base64 -d keystore-b64.txt > ./app/test.jks
      - name: Build APK
        env:
          VIM8_BUILD_KEYSTORE_FILE: ./test.jks
          VIM8_BUILD_KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          VIM8_BUILD_KEY_ALIAS: ${{ secrets.ALIAS }}
          VIM8_BUILD_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew assembleRelease
      - name: Create Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: changelog-configuration.json
          toTag: ${{github.sha}}
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: Nightly - ${{ env.date }}
          tag_name: nightly-${{ env.ts }}
          body: ${{steps.github_release.outputs.changelog}}
          prerelease: true
          files: app/build/outputs/apk/release/app-release.apk
