name: Pre-release deployment

on:
  push:
    tags: ["v*"]
jobs:
  version:
    name: Get app version
    uses: ./.github/workflows/extract-version.yaml
  playstore:
    name: Deploy the app to Google playstore
    needs: [version]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: temurin
          cache: gradle
      - name: Setup env
        run: |
          mkdir -p distribution/whatsnew
          cp metadata/en-US/changelogs/${{needs.version.outputs.version_code}}.txt distribution/whatsnew/whatsnew-en-US
          echo "${{ secrets.SIGNING_KEYSTORE_BASE64 }}" > keystore-b64.txt
          base64 -d keystore-b64.txt > 8vim/test.jks
      - name: Build APK
        env:
          VIM8_BUILD_KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          VIM8_BUILD_KEY_ALIAS: ${{ secrets.ALIAS }}
          VIM8_BUILD_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew bundleRelease
      - name: Google play release
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: tech.maethornaur.myapplication
          releaseFiles: 8vim/build/outputs/bundle/release/8vim-release.aab
          track: internal
          # status: draft
          whatsNewDirectory: distribution/whatsnew
          mappingFile: 8vim/build/outputs/mapping/release/mapping.txt
      - name: Upload artifact aab
        uses: actions/upload-artifact@v3
        with:
          name: aab
          path: 8vim/build/outputs/bundle/release/8vim-release.aab
  release:
    name: Create github release
    needs: [playstore]
    permissions:
      actions: read
      issues: read
      pull-requests: read
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        id: aab
        uses: actions/download-artifact@v3
        with:
          name: aab
      - name: Create Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: changelog-configuration.json
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{steps.github_release.outputs.changelog}}
          files: ${{ steps.aab.outputs.download-paths }}
          prerelease: true
  unrelease:
    name: Unrelease if an error happened
    needs: [playstore, release]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    if: ${{failure()}}
    steps:
      - uses: dev-drprasad/delete-tag-and-release@v1.0.1
        with:
          tag_name: ${{github.ref_name}}
          github_token: ${{ secrets.PAT }}
