name: Promote version
on:
  workflow_dispatch:
    inputs:
      from:
        description: Origin track
        default: internal
      to:
        description: New track
        default: alpha
jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - uses: kevin-david/promote-play-release@v1.0.0
        with:
          package-name: tech.maethornaur.myapplication
          service-account-json-raw: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          from-track: ${{github.event.inputs.from}}
          to-track: ${{github.event.inputs.to}}
