name: release

on: workflow_dispatch
jobs:
  version:
    name: Get app version
    runs-on: ubuntu-latest
    outputs:
      version_code: ${{steps.vars.outputs.version_code}}
      version_name: ${{steps.vars.outputs.version_name}}
    steps:
      - uses: actions/checkout@v3
      - name: Get version
        id: vars
        run: |
          set +a
          . ./app/version.properties
          set -a
          echo "version_code=$VERSION_CODE" >> $GITHUB_OUTPUT
          echo "version_name=$VERSION_NAME" >> $GITHUB_OUTPUT
  playstore:
    name: Deploy the app to Google playstore and create a release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          pwd
          ls -alh
      - name: Google play promote
        uses: The-Vincit-Group/promote-google-play-track-action@v1.0.0-alpha.2
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: tech.maethornaur.myapplication
          fromTrack: internal
          toTrack: beta
  f_droid:
    name: Release to F-droid
    needs: [version]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.PAT}}
          repository: MaethorNaur/MaethorNaur.github.io
          persist-credentials: false
      - run: |
          echo "{\"version_code\": ${{needs.version.outputs.version_code}}, \"version_name\": \"${{needs.version.outputs.version_name}}\"}" > version.json
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add version.json
          git commit -a -m "chore: release ${{needs.version.outputs.version_name}}"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          repository: MaethorNaur/MaethorNaur.github.io
  relase:
    name: Create github release
    needs: [f_droid, playstore]
    if: ${{always()}}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        uses: tubone24/update_release@v1.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          TAG_NAME: ${{needs.version.outputs.version_name}}
        with:
          prerelease: false
