name: release

on:
  push:
    tags: ["v*"]
jobs:
  test:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: vars
        id: vars
        run: |
          set +a
          . ./app/version.properties
          set -a
          echo "version_code=$VERSION_CODE" >> $GITHUB_OUTPUT
          mkdir -p distribution/whatsnew
          echo "release ${VERSION_NAME}" > distribution/whatsnew/whatsnew-en-US
      - uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: temurin
          cache: gradle
      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.SIGNING_KEYSTORE_BASE64 }}
        run: |
          echo "$ENCODED_STRING" > keystore-b64.txt
          base64 -d keystore-b64.txt > app/test.jks
      - name: Build APK
        env:
          VIM8_BUILD_KEYSTORE_FILE: ./test.jks
          VIM8_BUILD_KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          VIM8_BUILD_KEY_ALIAS: ${{ secrets.ALIAS }}
          VIM8_BUILD_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew bundleRelease
      - name: Google play release
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: tech.maethornaur.myapplication
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: internal
          status: draft
          whatsNewDirectory: distribution/whatsnew
          mappingFile: app/build/outputs/mapping/release/mapping.txt
      - name: Create Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: changelog-configuration.json
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{steps.github_release.outputs.changelog}}
          files: app/build/outputs/bundle/release/app-release.aab
