name: Sub
run-name: "Sub #${{github.event.workflow_run.pull_requests[0].number}}"
on:
  workflow_run:
    workflows: [t]
    types: [completed]

jobs:
  o:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{github.event.workflow_run.pull_requests}}"
