name: Sub
run-name: "Sub #${{github.event.workflow_run.pull_requests[0].number}}"
on:
  workflow_run:
    workflows: [t]
    types: [completed]

jobs:
  l:
    runs-on: ubuntu-latest
    outputs:
      metadata: ${{fromJson(steps.metadata.outputs.metadata)}}
    steps:
        - id: metadata
          uses: redhat-plumbers-in-action/gather-pull-request-metadata@v1
          with:
            pr-number: ${{github.event.workflow_run.pull_requests[0].number}}
  il:
    runs-on: ubuntu-latest
    needs: [l]
    if: ${{contains(needs.l.outputs.metadata.labels.*.name,'bug')}}
    steps:
      - run: echo "label"
  p:
    runs-on: ubuntu-latest
    outputs:
      a: ${{steps.step.outputs.a}}
      b: ${{steps.step.outputs.b}}
    steps:
      - id: step
        run: |
          echo "b=yolo"  >> $GITHUB_OUTPUT
  o:
    runs-on: ubuntu-latest
    needs: [p]
    if: ${{needs.p.outputs.b != null}}
    steps:
      - run: |
          echo "${{github.event.workflow_run.head_sha}}"
  no:
    runs-on: ubuntu-latest
    needs: [p]
    if: ${{needs.p.outputs.b == null}}
    steps:
      - run: |
          echo "empty"

