name: t
on:
  workflow_dispatch:
    inputs:
      a:
        type: string
      b:
        type: boolean
jobs:
  p:
    runs-on: ubuntu-latest
    steps:
      - uses: julbme/gh-action-manage-milestone@v1
        with:
          title: ${{inputs.a}}
          state: closed
        env:
          GITHUB_TOKEN: ${{ github.token  }}
          #${{ secrets.PAT }}
