name: t
on: 
  workflow_dispatch:
  pull_request:
    branches: [main]
  push: 
    branches: [main]

jobs:
  p:
    runs-on: ubuntu-latest
    outputs:
      a: ${{steps.step.outputs.a}}
      b: ${{steps.step.outputs.b}}
    steps:
      - id: step
        run: |
