name: t
on:
  workflow_dispatch:
    inputs:
      a:
        type: boolean
      b:
        type: boolean
jobs:
  p:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{inputs.a}} ${{input.b}}"
