name: t
on: [workflow_dispatch]

jobs:
  p:
    runs-on: ubuntu-latest
    outputs:
      a: ${{steps.step.outputs.a}}
      b: ${{steps.step.outputs.b}}
    steps:
      - id: step
        run: |
          echo "a=1"  >> $GITHUB_OUTPUT
  o:
    runs-on: ubuntu-latest
    needs: [p]
    steps:
      - env:
          B: ${{needs.p.outputs.b}}
        run: |
          echo "a: ${{needs.p.outputs.a}}"
          echo "b: $B"
