name: t
on:
  workflow_dispatch:
    inputs:
      a:
        type: string
      b:
        type: boolean
jobs:
  p:
    runs-on: ubuntu-latest
    steps:
      - uses: Beakyn/gha-close-milestone@v1.1.1
        with:
          milestone-title: ${{inputs.a}}
          repository: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ github.token  }}
          #${{ secrets.PAT }}
