name: t
on:
  workflow_dispatch:
    inputs:
      message:
        type: string
        required: true
jobs:
  p:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{inputs.message}}" > a.txt
          cat a.txt
