name: t
on: [workflow_dispatch]

jobs:
  p:
    runs-on: ubuntu-latest
    outputs:
      a: ${{steps.step.outputs.a}}
      b: ${{steps.step.outputs.b}}
    steps:
      - id: step
        run: |
          echo "b=1"  >> $GITHUB_OUTPUT
  o:
    needs: [p]
    uses: ./.github/workflows/s.yaml
    with:
      a: ${{needs.p.outputs.a}}
      b: ${{needs.p.outputs.b || -1}}
